# fly.toml app configuration file generated for truffle-server on 2023-12-01T19:08:00+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "truffle-server"
primary_region = "ams"

[build]
  image = "registry.fly.io/truffle-server:latest"

[env]
  PORT = "8080"
  POSTGRES_DB = "truffle-database.internal"
  POSTGRES_HOST = "truffle-database"
  POSTGRES_PASSWORD = "1s0Hb4jzkvuYupe"
  POSTGRES_PORT = "5432"
  POSTGRES_USER = "postgres"
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
